### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by Hanks10100** [songsiqi/weex-vue-migration#2]
## Features

+ [x] Convert lifecycle `ready` to `mounted`.
+ [ ] `data` property should also convert to `data`, not `props`.
+ [ ] Add `px` unit for CSS length property.
+ [x] Add `scoped` property on `<style>`.
+ [x] Conver `require('@weex-module/dom')` to  `weex.requireModule('dom')`

**Comment by songsiqi** [comment]
Feature 1, 4 and 5 are finished in 0.2.1 version.
