### ISSUE TITLE
image转成img的问题

### ISSUE THREAD

**Issue by dongnaebi** [songsiqi/weex-vue-migration#3]
image转成img的后，weex-loader没有做img非闭合标签的处理，导致img后面的标签不能正常显示。

**Comment by songsiqi** [comment]
@Hanks10100 一起看下

**Comment by Hanks10100** [comment]
@dongnaebi 能否再说的详细些，image 什么情况下会转换成 img ？如果是 web 中浏览器自动转换的话， img 标签不需要结束标签的。

**Comment by dongnaebi** [comment]
就是`weex-vue-migration path`转成.vue的时候，image标签变成了img，web中是正常的。但在native端就不行了。也可能是版本问题？大概2周以前转.vue的，前两天在native端看才发现的问题。。。

**Comment by Hanks10100** [comment]
@dongnaebi 希望你能再明确一下问题吧

**Comment by songsiqi** [comment]
@dongnaebi  0.2.4版本已修复
